"""empty message

Revision ID: 428987c2c3e0
Revises: e2f8aed01f26
Create Date: 2021-05-23 05:13:16.649533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428987c2c3e0'
down_revision = 'e2f8aed01f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
